name: Publish Package to NPM and GitHub Packages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js v22
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # ------------------------------------------
      # --- Publish to NPM Registry (npmjs.com) ---
      # ------------------------------------------
      - name: Configure NPM for public registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to NPM Registry
        run: npm publish --access=public
        # env:
        #  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # ----------------------------------------
      # --- Publish to GitHub Packages (GPR) ---
      # ----------------------------------------
      - name: Configure NPM for GitHub Packages registry
        run: |
          echo "@mgks:registry=https://npm.pkg.github.com" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}